### ISSUE TITLE
Produktiv - Handbuch mit eigener Domain aufsetzen

### ISSUE THREAD

**Issue by specka** [zalf-rdm/bonares-handbook#8]
**What is the task about | Worum geht es bei dieser Aufgabe**

Das mit Markdown und Retype aufgesetzte Handbuch zum BonaRes Repository ist nun bereit, veröffentlicht zu werden. Dazu muss das System analog wie der BonaRes Standards-Report auf einem Server laufen (oder in einem Docker-Container zum laufen gebracht werden).

**Which steps are on the way to solve this task | Welche Schritte müssen für diese Aufgabe erledigt werden**
  1. Domain repository-handbooks.dataservice.zalf.de bei der ZALF IT beantragen
  2. Prüfen, wie das Produktiv-System bei uns zum Laufen gebracht werden kann (wie BonaRes Standards Report, oder einem Docker-Container); wo läuft das System
  3. Workflow entwickeln, dass Updates auf die Produktiv-Version eingespielt werden können; die Testversion muss weiterhin unter https://zalf-rdm.github.io/bonares-handbook/ laufen.

@thomas-zalf und @silvadealmeida Bitte sprecht euch untereinander ab, wie das ganze umgesetzt werden soll. Thomas weiß, was beim Standards Report gemacht wurde, Igo hat die Infos zum aktuellen Repo-Handbuch Projekt. Und dieser Use Case sollte so gedacht werden, dass weitere Handbücher (z.B. für Profil-Datenbank) in einer ähnlichen Art und Weise bereitgestellt werden können.

**Comment by silvadealmeida** [comment]
Avalibles
[https://handbooks.dataservice.zalf.de](https://handbooks.dataservice.zalf.de)
[https://handbooks.dataservice.zalf.de/bonares-repository](https://handbooks.dataservice.zalf.de/bonares-repository)
